version: '3'
services:
  web:
    image: webserver
    build: /root/project/final
    container_name: apache-webserver
    ports:
      - "8080:80"
  db:
    image: mongo-db
    build: /root/project/final
    container_name: mongo-dbserver
    ports:
      - "2717:27017"
  zookeeper:
    image: zookeeper
    build: /root/project/final
    container_name: zookeeper-container
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: true  
  kafka:
    image: apache-kafka
    build: /root/project/final
    container_name: kafka-server
    ports:
      - "9092"
    environment:
    KAFKA_ADVERTISED_HOST_NAME: 54.242.207.124
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  