version: '3'
services:
  web:
    image: webserver
    build: /root/project/final
    container_name: apache-webserver
    ports:
      - "8080:80"
  db:
    image: mongo-db
    build: /root/project/final
    container_name: mongo-dbserver
    ports:
      - "2717:27017"
