# Apache Image
FROM ubuntu:latest AS webserver
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils
RUN apt-get clean
RUN echo "Hello World!" > /var/www/html/index.html
CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
EXPOSE 80

# MongoDB Image
FROM ubuntu AS mongo-db
RUN apt-get update && apt-get install -y gnupg2
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' > tee /etc/apt/sources.list.d/mongodb.list
RUN apt-get update
RUN apt-get install -y mongodb
RUN mkdir -p /data/db
EXPOSE 27017
HEALTHCHECK --interval=5s --timeout=3s CMD pgrep mongo || exit 1
CMD ["usr/bin/mongod", "--smallfiles"]
